# Generated by Django 5.2.4 on 2025-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_phone_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_id',
        ),
        migrations.AddField(
            model_name='part',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
