# Generated by Django 5.2.4 on 2025-08-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_part_part_id_part_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('price_at_time_of_use', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='api.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.part')),
            ],
        ),
    ]
