# Generated by Django 5.2.5 on 2025-08-20 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invoice_created_at_alter_jobcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
